In [69]:
import pandas as pd
import pandera as pa

In [70]:
valores_ausentes = ['**','###!','####','****','****','*****','NULL']
df = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BEL?M,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PAR? DE MINAS,MG,NaN,2010-01-10,20:00:00,0

In [71]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo":pa.Column(pa.Int, required=False),
        "codigo_ocorrencia":pa.Column(pa.Int),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True)
    }
)

In [72]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BEL?M,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,02:30:00,0
6111,80251,80251,INCIDENTE,BEL?M,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,NaN,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [73]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [74]:
df.loc[1]

codigo_ocorrencia                         40349
codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BEL?M
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                           0
Name: 1, dtype: object

In [75]:
df.iloc[1]

codigo_ocorrencia                         40349
codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BEL?M
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                           0
Name: 1, dtype: object

In [76]:
df.iloc[-1]

codigo_ocorrencia                         80259
codigo_ocorrencia2                        80259
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                      CAMPINAS
ocorrencia_uf                                SP
ocorrencia_aerodromo                       SBKP
ocorrencia_dia              2021-08-18 00:00:00
ocorrencia_hora                        12:45:00
total_recomendacoes                           0
Name: 6113, dtype: object

In [77]:
df.tail()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,02:30:00,0
6111,80251,80251,INCIDENTE,BEL?M,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,NaN,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [78]:
df.iloc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789,39789,INCIDENTE,S?O PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0
11,40069,40069,ACIDENTE,S?O PAULO,SP,SBMT,2010-01-10,14:50:00,8
12,40414,40414,INCIDENTE,BRAS?LIA,DF,SBBR,2010-01-10,03:00:00,0
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2
14,40107,40107,ACIDENTE,GURUP?,PA,SNGU,2010-01-12,14:30:00,0

In [79]:
df.loc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789,39789,INCIDENTE,S?O PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0
11,40069,40069,ACIDENTE,S?O PAULO,SP,SBMT,2010-01-10,14:50:00,8
12,40414,40414,INCIDENTE,BRAS?LIA,DF,SBBR,2010-01-10,03:00:00,0
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2
14,40107,40107,ACIDENTE,GURUP?,PA,SNGU,2010-01-12,14:30:00,0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0

In [80]:
df.loc[:,'ocorrencia_uf']

0       RJ
1       PA
2       RJ
3       MT
4       RS
        ..
6109    PE
6110    RO
6111    PA
6112    MT
6113    SP
Name: ocorrencia_uf, Length: 6114, dtype: object

In [81]:
df['ocorrencia_uf']

0       RJ
1       PA
2       RJ
3       MT
4       RS
        ..
6109    PE
6110    RO
6111    PA
6112    MT
6113    SP
Name: ocorrencia_uf, Length: 6114, dtype: object

In [82]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        2456
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [83]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        2456
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [84]:
filtro = df.ocorrencia_uf.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2227,49474,49474,ACIDENTE,?GUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0
5855,79956,79956,ACIDENTE,N?O IDENTIFICADA,NaN,NaN,2021-02-26,11:00:00,0

In [85]:
filtro = df.ocorrencia_aerodromo.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
9,39711,39711,INCIDENTE GRAVE,PAR? DE MINAS,MG,NaN,2010-01-10,20:00:00,0
...,...,...,...,...,...,...,...,...,...
6092,80236,80236,ACIDENTE,POCON?,MT,NaN,2021-08-01,22:00:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0
6096,80229,80229,INCIDENTE,ITAGUA?,RJ,NaN,2021-08-05,15:30:00,0
6099,80233,80233,ACIDENTE,POCON?,MT,NaN,2021-08-08,12:30:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,NaN,2021-08-18,16:00:00,0

In [86]:
filtro = df.ocorrencia_hora.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
4102,78823,78823,INCIDENTE,CORUMB?,MS,NaN,2017-07-09,NaN,0

In [87]:
df.count()

codigo_ocorrencia           6114
codigo_ocorrencia2          6114
ocorrencia_classificacao    6114
ocorrencia_cidade           6114
ocorrencia_uf               6112
ocorrencia_aerodromo        3658
ocorrencia_dia              6114
ocorrencia_hora             6113
total_recomendacoes         6114
dtype: int64

In [88]:
#ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
63,39992,39992,ACIDENTE,S?O PAULO,SP,SBMT,2010-02-17,20:07:00,11
326,42250,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19
530,43471,43471,ACIDENTE,S?O PAULO,SP,NaN,2010-12-14,20:15:00,11
727,44377,44377,ACIDENTE,IT?POLIS,SP,SDIO,2011-04-09,14:50:00,11
872,44796,44796,ACIDENTE,RECIFE,PE,SBRF,2011-07-13,09:54:00,23
884,44888,44888,INCIDENTE GRAVE,S?O JOS? DOS PINHAIS,PR,SBCT,2011-07-15,17:05:00,11
1062,45554,45554,INCIDENTE GRAVE,UBERL?NDIA,MG,SBUL,2011-11-15,02:15:00,20
1972,47938,47938,INCIDENTE,BRAS?LIA,DF,SBBR,2013-04-13,18:00:00,11
2797,52265,52265,ACIDENTE,SANTOS,SP,NaN,2014-08-13,13:03:00,13
3932,66432,66432,INCIDENTE GRAVE,VIT?RIA,ES,NaN,2017-02-21,11:47:00,12

In [89]:
#ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade','total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
63               S?O PAULO                   11
326         RIO DE JANEIRO                   19
530              S?O PAULO                   11
727               IT?POLIS                   11
872                 RECIFE                   23
884   S?O JOS? DOS PINHAIS                   11
1062            UBERL?NDIA                   20
1972              BRAS?LIA                   11
2797                SANTOS                   13
3932               VIT?RIA                   12

In [90]:
#ocorrências cuja classificação == incidente grave
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PAR? DE MINAS,MG,NaN,2010-01-10,20:00:00,0
29,39709,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0
...,...,...,...,...,...,...,...,...,...
6090,80221,80221,INCIDENTE GRAVE,MARA?,BA,SIRI,2021-07-31,13:15:00,0
6095,80228,80228,INCIDENTE GRAVE,ELDORADO DO SUL,RS,SIXE,2021-08-05,15:55:00,0
6097,80231,80231,INCIDENTE GRAVE,CAXIAS DO SUL,RS,SBCX,2021-08-06,16:59:00,0
6098,80248,80248,INCIDENTE GRAVE,CHAPAD?O DO SUL,MS,SSCD,2021-08-06,20:00:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0

In [91]:
#ocorrências cuja classificação == INCIDENTE GRAVE e o estado == SP
filtro2 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro1 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
136,40270,40270,INCIDENTE GRAVE,PIRASSUNUNGA,SP,SDPY,2010-04-15,20:15:00,0
171,40620,40620,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2010-05-06,15:50:00,0
219,41411,41411,INCIDENTE GRAVE,S?O PAULO,SP,SBMT,2010-06-08,19:30:00,2
297,42289,42289,INCIDENTE GRAVE,S?O PAULO,SP,SBMT,2010-07-29,20:06:00,0
314,42323,42323,INCIDENTE GRAVE,S?O JOS? DO RIO PRETO,SP,SBSR,2010-08-05,12:01:00,0
...,...,...,...,...,...,...,...,...,...
5949,80056,80056,INCIDENTE GRAVE,FERNAND?POLIS,SP,NaN,2021-04-28,11:20:00,0
6000,80114,80114,INCIDENTE GRAVE,LINS,SP,SWXQ,2021-06-05,19:43:00,0
6007,80124,80124,INCIDENTE GRAVE,S?O PAULO,SP,SBSP,2021-06-10,20:30:00,0
6081,80200,80200,INCIDENTE GRAVE,BRAGAN?A PAULISTA,SP,SDVH,2021-07-25,12:25:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0

In [92]:
#ocorrências cuja classificação == INCIDENTE GRAVE ou o estado == SP
filtro2 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro1 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PAR? DE MINAS,MG,NaN,2010-01-10,20:00:00,0
11,40069,40069,ACIDENTE,S?O PAULO,SP,SBMT,2010-01-10,14:50:00,8
16,39809,39809,INCIDENTE,S?O PAULO,SP,NaN,2010-01-15,15:00:00,0
...,...,...,...,...,...,...,...,...,...
6097,80231,80231,INCIDENTE GRAVE,CAXIAS DO SUL,RS,SBCX,2021-08-06,16:59:00,0
6098,80248,80248,INCIDENTE GRAVE,CHAPAD?O DO SUL,MS,SSCD,2021-08-06,20:00:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
6108,80244,80244,INCIDENTE,BRAGAN?A PAULISTA,SP,SBBP,2021-08-15,15:20:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [93]:
#ocorrências cuja (classificação == INCIDENTE GRAVE ou classificacao == INCIDENTE) e o estado == SP
#filtro2 = (df.ocorrencia_classificacao == 'INCIDENTE GRAVE') | (df.ocorrencia_classificacao == 'INCIDENTE')
filtro2 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE','INCIDENTE'])
filtro1 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809,39809,INCIDENTE,S?O PAULO,SP,NaN,2010-01-15,15:00:00,0
18,39828,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0
33,39848,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0
...,...,...,...,...,...,...,...,...,...
6084,80234,80234,INCIDENTE,S?O PAULO,SP,SBSP,2021-07-26,13:20:00,0
6085,80208,80208,INCIDENTE,S?O PAULO,SP,SBMT,2021-07-27,19:45:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
6108,80244,80244,INCIDENTE,BRAGAN?A PAULISTA,SP,SBBP,2021-08-15,15:20:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [94]:
#ocorrências cuja cidade comecem com a letra C
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
20,40310,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0
...,...,...,...,...,...,...,...,...,...
6094,80225,80225,INCIDENTE,CURITIBA,PR,SBBI,2021-08-04,13:45:00,0
6097,80231,80231,INCIDENTE GRAVE,CAXIAS DO SUL,RS,SBCX,2021-08-06,16:59:00,0
6098,80248,80248,INCIDENTE GRAVE,CHAPAD?O DO SUL,MS,SSCD,2021-08-06,20:00:00,0
6100,80235,80235,INCIDENTE,CORUMB?,MS,SBCR,2021-08-09,20:55:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [95]:
#ocorrências cuja cidade comecem com a letra A
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
12,40414,40414,INCIDENTE,BRAS?LIA,DF,SBBR,2010-01-10,03:00:00,0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
25,39772,39772,INCIDENTE,UBERL?NDIA,MG,NaN,2010-01-20,18:58:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
...,...,...,...,...,...,...,...,...,...
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0
6094,80225,80225,INCIDENTE,CURITIBA,PR,SBBI,2021-08-04,13:45:00,0
6102,80240,80240,INCIDENTE,GOI?NIA,GO,SBNV,2021-08-10,14:15:00,0
6104,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
6108,80244,80244,INCIDENTE,BRAGAN?A PAULISTA,SP,SBBP,2021-08-15,15:20:00,0

In [96]:
#ocorrências cuja cidade terminam com os caracteres MA
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
408,43062,43062,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1
688,44198,44198,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0
1035,51785,51785,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0
1377,45939,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0
1401,46180,46180,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0
2099,49113,49113,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4
2102,48799,48799,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0
2646,80059,80059,INCIDENTE,IVINHEMA,MS,NaN,2014-04-27,11:30:00,0
2657,51347,51347,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0
2857,52340,52340,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1
2968,52832,52832,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0
2999,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
3042,52984,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0
3094,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0
3159,53223,53223,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0
3173,53265,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2
3191,53271,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0
3684,65414,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1
3727,65633,65633,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0
3883,66265,66265,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0
4231,77371,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1
4313,77612,77612,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0
4576,78080,78080,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0
4987,78867,78867,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,00:00:00,0
5071,78923,78923,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0
5081,78782,78782,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0
5406,79282,79282,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0
5441,79338,79338,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,09:40:00,0
5475,79400,79400,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0
5759,79823,79823,ACIDENTE,IRACEMA,RR,NaN,2021-01-05,20:07:00,0
5776,79820,79820,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,09:27:00,0
5778,79830,79830,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,09:27:00,0
5861,79943,79943,INCIDENTE,IBOTIRAMA,BA,SNIT,2021-03-03,11:30:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0

In [97]:
#ocorrências cuja cidade contém (em qualquer parte do conteúdo) os caracteres MA
filtro = df.ocorrencia_cidade.str.contains('MA')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0
78,39916,39916,INCIDENTE GRAVE,MANAUS,AM,SBEG,2010-03-07,19:35:00,2
...,...,...,...,...,...,...,...,...,...
6075,80205,80205,INCIDENTE,MANAUS,AM,SBEG,2021-07-23,11:15:00,0
6086,80212,80212,INCIDENTE,AMAP?,AP,NaN,2021-07-28,18:00:00,0
6090,80221,80221,INCIDENTE GRAVE,MARA?,BA,SIRI,2021-07-31,13:15:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0
6106,80249,80249,INCIDENTE,MANAUS,AM,SBEG,2021-08-14,15:40:00,0

In [98]:
#ocorrências cuja cidade contém (em qualquer parte do conteúdo) os caracteres MA ou AL
filtro = df.ocorrencia_cidade.str.contains('MA|AL')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
17,39810,39810,INCIDENTE,SALVADOR,BA,NaN,2010-01-15,18:23:00,0
...,...,...,...,...,...,...,...,...,...
6075,80205,80205,INCIDENTE,MANAUS,AM,SBEG,2021-07-23,11:15:00,0
6086,80212,80212,INCIDENTE,AMAP?,AP,NaN,2021-07-28,18:00:00,0
6090,80221,80221,INCIDENTE GRAVE,MARA?,BA,SIRI,2021-07-31,13:15:00,0
6093,80227,80227,ACIDENTE,UMUARAMA,PR,NaN,2021-08-02,14:30:00,0
6106,80249,80249,INCIDENTE,MANAUS,AM,SBEG,2021-08-14,15:40:00,0

In [99]:
#ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2998,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3
2999,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
3000,53073,53073,INCIDENTE,TEF?,AM,SBTF,2015-01-02,16:28:00,0
3001,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0
3002,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6
...,...,...,...,...,...,...,...,...,...
3464,60632,60632,INCIDENTE GRAVE,ITABER?,SP,NaN,2015-12-24,14:00:00,0
3465,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3466,60642,60642,INCIDENTE,S?O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3467,60631,60631,ACIDENTE,MA?AMBAR?,RS,NaN,2015-12-28,19:00:00,2
3468,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [100]:
#ocorrências do ano de 2015 e mês 12
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3430,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0
3431,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0
3432,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0
3433,53636,53636,INCIDENTE,JUNDIA?,SP,SBJD,2015-12-02,17:42:00,0
3434,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
3435,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
3436,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
3437,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3440,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0
3442,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0
3443,60604,60604,INCIDENTE,GOI?NIA,GO,SBGO,2015-12-12,14:34:00,0
3444,60611,60611,INCIDENTE,S?O PAULO,SP,SBSP,2015-12-12,15:30:00,0
3445,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0
3446,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0
3447,53630,53630,INCIDENTE,MAR?LIA,SP,SBML,2015-12-13,13:50:00,0
3448,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0
3449,60612,60612,ACIDENTE,BENTO GON?ALVES,RS,SSBG,2015-12-13,20:30:00,0
3450,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3
3451,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0
3452,60609,60609,INCIDENTE GRAVE,ARAGUA?NA,TO,SWGN,2015-12-15,13:00:00,0
3453,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0
3454,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4
3455,60645,60645,ACIDENTE,SERT?OZINHO,SP,NaN,2015-12-15,13:00:00,0
3456,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0
3457,60625,60625,ACIDENTE,IT?POLIS,SP,SDIO,2015-12-17,21:30:00,1
3458,60605,60605,INCIDENTE,UBERL?NDIA,MG,SBUL,2015-12-18,10:25:00,0
3459,60610,60610,INCIDENTE,JUNDIA?,SP,SBJD,2015-12-18,18:45:00,0
3460,60602,60602,INCIDENTE,RIBEIR?O PRETO,SP,SBRP,2015-12-22,06:27:00,0
3461,60615,60615,INCIDENTE,S?O PAULO,SP,SBMT,2015-12-22,13:07:00,0
3462,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0
3463,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0
3464,60632,60632,INCIDENTE GRAVE,ITABER?,SP,NaN,2015-12-24,14:00:00,0
3465,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3466,60642,60642,INCIDENTE,S?O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3467,60631,60631,ACIDENTE,MA?AMBAR?,RS,NaN,2015-12-28,19:00:00,2
3468,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [101]:
#ocorrências do ano de 2015 e mês 12
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3430,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0
3431,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0
3432,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0
3433,53636,53636,INCIDENTE,JUNDIA?,SP,SBJD,2015-12-02,17:42:00,0
3434,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
3435,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
3436,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
3437,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3440,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0
3442,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0
3443,60604,60604,INCIDENTE,GOI?NIA,GO,SBGO,2015-12-12,14:34:00,0
3444,60611,60611,INCIDENTE,S?O PAULO,SP,SBSP,2015-12-12,15:30:00,0
3445,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0
3446,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0
3447,53630,53630,INCIDENTE,MAR?LIA,SP,SBML,2015-12-13,13:50:00,0
3448,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0
3449,60612,60612,ACIDENTE,BENTO GON?ALVES,RS,SSBG,2015-12-13,20:30:00,0
3450,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3
3451,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0
3452,60609,60609,INCIDENTE GRAVE,ARAGUA?NA,TO,SWGN,2015-12-15,13:00:00,0
3453,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0
3454,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4
3455,60645,60645,ACIDENTE,SERT?OZINHO,SP,NaN,2015-12-15,13:00:00,0
3456,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0
3457,60625,60625,ACIDENTE,IT?POLIS,SP,SDIO,2015-12-17,21:30:00,1
3458,60605,60605,INCIDENTE,UBERL?NDIA,MG,SBUL,2015-12-18,10:25:00,0
3459,60610,60610,INCIDENTE,JUNDIA?,SP,SBJD,2015-12-18,18:45:00,0
3460,60602,60602,INCIDENTE,RIBEIR?O PRETO,SP,SBRP,2015-12-22,06:27:00,0
3461,60615,60615,INCIDENTE,S?O PAULO,SP,SBMT,2015-12-22,13:07:00,0
3462,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0
3463,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0
3464,60632,60632,INCIDENTE GRAVE,ITABER?,SP,NaN,2015-12-24,14:00:00,0
3465,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3466,60642,60642,INCIDENTE,S?O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3467,60631,60631,ACIDENTE,MA?AMBAR?,RS,NaN,2015-12-28,19:00:00,2
3468,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [102]:
#ocorrências do ano de 2015 e mês 12
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3430,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0
3431,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0
3432,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0
3433,53636,53636,INCIDENTE,JUNDIA?,SP,SBJD,2015-12-02,17:42:00,0
3434,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
3435,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
3436,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
3437,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3440,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0
3442,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0
3443,60604,60604,INCIDENTE,GOI?NIA,GO,SBGO,2015-12-12,14:34:00,0
3444,60611,60611,INCIDENTE,S?O PAULO,SP,SBSP,2015-12-12,15:30:00,0
3445,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0
3446,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0
3447,53630,53630,INCIDENTE,MAR?LIA,SP,SBML,2015-12-13,13:50:00,0
3448,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0
3449,60612,60612,ACIDENTE,BENTO GON?ALVES,RS,SSBG,2015-12-13,20:30:00,0
3450,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3
3451,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0
3452,60609,60609,INCIDENTE GRAVE,ARAGUA?NA,TO,SWGN,2015-12-15,13:00:00,0
3453,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0
3454,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4
3455,60645,60645,ACIDENTE,SERT?OZINHO,SP,NaN,2015-12-15,13:00:00,0
3456,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0
3457,60625,60625,ACIDENTE,IT?POLIS,SP,SDIO,2015-12-17,21:30:00,1
3458,60605,60605,INCIDENTE,UBERL?NDIA,MG,SBUL,2015-12-18,10:25:00,0
3459,60610,60610,INCIDENTE,JUNDIA?,SP,SBJD,2015-12-18,18:45:00,0
3460,60602,60602,INCIDENTE,RIBEIR?O PRETO,SP,SBRP,2015-12-22,06:27:00,0
3461,60615,60615,INCIDENTE,S?O PAULO,SP,SBMT,2015-12-22,13:07:00,0
3462,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0
3463,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0
3464,60632,60632,INCIDENTE GRAVE,ITABER?,SP,NaN,2015-12-24,14:00:00,0
3465,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3466,60642,60642,INCIDENTE,S?O FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3467,60631,60631,ACIDENTE,MA?AMBAR?,RS,NaN,2015-12-28,19:00:00,2
3468,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [103]:
#ocorrências do ano de 2015 e mês 12
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia = df.ocorrencia_dia.dt.day == 8
df.loc[filtro_ano & filtro_mes & filtro_dia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3440,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [104]:
#ocorrências do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia_inicio = df.ocorrencia_dia.dt.day > 2
filtro_dia_fim = df.ocorrencia_dia.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3434,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
3435,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
3436,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
3437,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3440,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [105]:
df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora

0       2010-01-03 12:00:00
1       2010-01-03 11:05:00
2       2010-01-03 03:00:00
3       2010-01-04 17:30:00
4       2010-01-05 19:25:00
               ...
6109    2021-08-15 15:05:00
6110    2021-08-16 02:30:00
6111    2021-08-17 15:45:00
6112    2021-08-18 16:00:00
6113    2021-08-18 12:45:00
Length: 6114, dtype: object

In [106]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

In [107]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BEL?M,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,2010-01-05 19:25:00

In [108]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [109]:
#ocorrências do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = df.ocorrencia_dia_hora.dt.year == 2015
filtro_mes = df.ocorrencia_dia_hora.dt.month == 12
filtro_dia_inicio = df.ocorrencia_dia_hora.dt.day > 2
filtro_dia_fim = df.ocorrencia_dia_hora.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3434,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,2015-12-03 10:50:00
3435,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
3436,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,2015-12-06 13:10:00
3437,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1,2015-12-08 14:30:00
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
3440,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,2015-12-08 16:19:00
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [110]:
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 14:30:00'
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3435,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
3436,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,2015-12-06 13:10:00
3437,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
3438,53628,53628,ACIDENTE,AGUA?,SP,NaN,2015-12-08,14:30:00,1,2015-12-08 14:30:00
3439,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
3441,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [111]:
df201503.count()

codigo_ocorrencia           6
codigo_ocorrencia2          6
ocorrencia_classificacao    6
ocorrencia_cidade           6
ocorrencia_uf               6
ocorrencia_aerodromo        4
ocorrencia_dia              6
ocorrencia_hora             6
total_recomendacoes         6
ocorrencia_dia_hora         6
dtype: int64

In [112]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           3
INCIDENTE          2
INCIDENTE GRAVE    1
Name: codigo_ocorrencia, dtype: int64

In [113]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE           1
INCIDENTE          2
INCIDENTE GRAVE    1
Name: ocorrencia_aerodromo, dtype: int64

In [114]:
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           3
INCIDENTE          2
INCIDENTE GRAVE    1
dtype: int64

In [115]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
ACIDENTE           3
INCIDENTE          2
INCIDENTE GRAVE    1
dtype: int64

In [116]:
filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP','MG','ES','RJ'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
9,39711,39711,INCIDENTE GRAVE,PAR? DE MINAS,MG,NaN,2010-01-10,20:00:00,0,2010-01-10 20:00:00
11,40069,40069,ACIDENTE,S?O PAULO,SP,SBMT,2010-01-10,14:50:00,8,2010-01-10 14:50:00
16,39809,39809,INCIDENTE,S?O PAULO,SP,NaN,2010-01-15,15:00:00,0,2010-01-15 15:00:00
...,...,...,...,...,...,...,...,...,...,...
541,43722,43722,ACIDENTE,CAJOBI,SP,NaN,2010-12-23,11:00:00,0,2010-12-23 11:00:00
544,43548,43548,INCIDENTE,S?O PAULO,SP,SBSP,2010-12-26,22:10:00,0,2010-12-26 22:10:00
548,43724,43724,ACIDENTE,COSM?POLIS,SP,NaN,2010-12-29,12:00:00,0,2010-12-29 12:00:00
550,43730,43730,INCIDENTE,VIT?RIA,ES,NaN,2010-12-30,18:10:00,0,2010-12-30 18:10:00
551,43975,43975,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0,2010-12-30 14:28:00

In [117]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            40
INCIDENTE          170
INCIDENTE GRAVE     18
dtype: int64

In [134]:
dfsudeste2010.groupby(['ocorrencia_uf','ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
ES             INCIDENTE                    5
MG             ACIDENTE                     7
               INCIDENTE                   39
               INCIDENTE GRAVE              5
RJ             ACIDENTE                     9
               INCIDENTE                   52
               INCIDENTE GRAVE              4
SP             ACIDENTE                    24
               INCIDENTE                   74
               INCIDENTE GRAVE              9
dtype: int64

In [135]:
dfsudeste2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
RIO DE JANEIRO           47
S?O PAULO                33
GUARULHOS                18
BELO HORIZONTE           17
CAMPINAS                 13
MACA?                    12
CONFINS                   7
UBERL?NDIA                5
JUIZ DE FORA              4
VIT?RIA                   4
MAR?LIA                   3
S?O JOS? DO RIO PRETO     3
S?O JOS? DOS CAMPOS       3
JUNDIA?                   2
PO?OS DE CALDAS           2
RIBEIR?O PRETO            2
IPATINGA                  2
BAURU                     2
DIVIN?POLIS               2
AREALVA                   2
CAMPOS DOS GOYTACAZES     2
MONTES CLAROS             2
SOROCABA                  2
UBERABA                   2
ARARAQUARA                2
ITANHA?M                  2
PIRACICABA                1
PIRASSUNUNGA              1
PIACATU                   1
ARRAIAL DO CABO           1
POUSO ALEGRE              1
RESENDE                   1
PAR? DE MINAS             1
S?O BERNARDO DO CAMPO     1
SANTOS                    1
SERRA NEGRA               1
TIM?TEO                   1
PEN?POLIS                 1
BOM JESUS DO AMPARO       1
OL?MPIA                   1
NOVO HORIZONTE            1
BRAGAN?A PAULISTA         1
BROTAS                    1
CAJOBI                    1
CAMANDUCAIA               1
BOITUVA                   1
CASIMIRO DE ABREU         1
BOCAINA                   1
COROMANDEL                1
COSM?POLIS                1
DIAMANTINA                1
BEBEDOURO                 1
IPER?                     1
IT?POLIS                  1
ARA?ATUBA                 1
LINHARES                  1
MANGARATIBA               1
BOM JESUS DO GALHO        1
AMERICANA                 1
dtype: int64

In [137]:
filtro = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
19,44575,44575,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-17,12:27:00,0,2010-01-17 12:27:00
23,40311,40311,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,13:20:00,0,2010-01-19 13:20:00
24,41577,41577,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,12:16:00,0,2010-01-19 12:16:00
30,39849,39849,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-23,03:30:00,0,2010-01-23 03:30:00
39,40617,40617,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-27,20:06:00,0,2010-01-27 20:06:00
49,39295,39295,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-02-06,21:09:00,0,2010-02-06 21:09:00
71,39987,39987,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-02-24,19:37:00,0,2010-02-24 19:37:00
101,40210,40210,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-03-20,20:02:00,0,2010-03-20 20:02:00
105,40209,40209,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-03-21,13:46:00,0,2010-03-21 13:46:00
107,40330,40330,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-03-24,11:35:00,0,2010-03-24 11:35:00
119,40190,40190,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,02:35:00,3,2010-04-06 02:35:00
139,40294,40294,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-04-16,20:00:00,0,2010-04-16 20:00:00
144,40293,40293,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-04-18,16:23:00,0,2010-04-18 16:23:00
154,40581,40581,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-04-21,13:20:00,0,2010-04-21 13:20:00
164,40774,40774,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-05-01,02:10:00,0,2010-05-01 02:10:00
185,41573,41573,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-05-13,16:10:00,0,2010-05-13 16:10:00
223,41591,41591,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-06-10,17:30:00,0,2010-06-10 17:30:00
240,41678,41678,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-06-19,19:05:00,0,2010-06-19 19:05:00
242,42011,42011,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-06-19,13:16:00,0,2010-06-19 13:16:00
248,41729,41729,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-06-25,13:05:00,0,2010-06-25 13:05:00
274,41750,41750,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3,2010-07-12 19:53:00
284,42067,42067,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-07-20,12:41:00,0,2010-07-20 12:41:00
296,42634,42634,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-07-28,10:05:00,0,2010-07-28 10:05:00
298,42436,42436,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-29,19:12:00,0,2010-07-29 19:12:00
300,42619,42619,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-07-30,09:24:00,0,2010-07-30 09:24:00
309,42443,42443,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-08-04,13:27:00,0,2010-08-04 13:27:00
319,42284,42284,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-08-10,12:30:00,0,2010-08-10 12:30:00
326,42250,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19,2010-08-12 12:26:00
335,42456,42456,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-21,16:35:00,0,2010-08-21 16:35:00
336,42740,42740,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-21,13:25:00,0,2010-08-21 13:25:00
341,42486,42486,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-23,23:55:00,0,2010-08-23 23:55:00
352,42603,42603,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-27,13:27:00,0,2010-08-27 13:27:00
359,42598,42598,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-31,12:35:00,0,2010-08-31 12:35:00
375,42714,42714,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,NaN,2010-09-11,15:30:00,0,2010-09-11 15:30:00
377,42868,42868,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-09-11,20:30:00,0,2010-09-11 20:30:00
386,43064,43064,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-09-15,17:54:00,0,2010-09-15 17:54:00
388,42880,42880,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBJR,2010-09-17,13:55:00,0,2010-09-17 13:55:00
389,42882,42882,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBJR,2010-09-17,18:46:00,0,2010-09-17 18:46:00
427,43578,43578,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-10-04,12:30:00,0,2010-10-04 12:30:00
432,43033,43033,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-10-05,21:46:00,0,2010-10-05 21:46:00
456,43699,43699,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-10-23,17:43:00,0,2010-10-23 17:43:00
494,43283,43283,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-11-20,13:02:00,0,2010-11-20 13:02:00
526,43527,43527,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-12-12,19:00:00,0,2010-12-12 19:00:00
527,43462,43462,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBGL,2010-12-13,11:00:00,0,2010-12-13 11:00:00
536,43921,43921,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-12-18,13:15:00,0,2010-12-18 13:15:00

In [138]:
filtro1 = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
filtro2 = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
119,40190,40190,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,02:35:00,3,2010-04-06 02:35:00
274,41750,41750,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3,2010-07-12 19:53:00
326,42250,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19,2010-08-12 12:26:00

In [126]:
filtro = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro].total_recomendacoes.sum()

25

In [144]:
dfsudeste2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBAE     0
SBAQ     0
SBBH     0
SBBP     9
SBBU     0
SBCF     0
SBGL     3
SBGR     0
SBIP     0
SBJD     7
SBJR     3
SBKP     0
SBME     0
SBMK     0
SBML     0
SBMT    27
SBPC     0
SBPR     1
SBRJ    19
SBRP     0
SBSJ     0
SBSP     0
SBSR     0
SBUL     0
SBUR     0
SBVT     0
SDAM     0
SDOI     1
SDPW     0
SDPY     0
SNDT     0
SNDV     0
SNXT     0
NaN     45
Name: total_recomendacoes, dtype: int64

In [149]:
dfsudeste2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0
ARA?ATUBA                 0
ARARAQUARA                0
AREALVA                   0
ARRAIAL DO CABO           0
BAURU                     0
BEBEDOURO                 0
BELO HORIZONTE            2
BOCAINA                   0
BOITUVA                   1
BOM JESUS DO AMPARO       0
BOM JESUS DO GALHO        1
BRAGAN?A PAULISTA         9
BROTAS                    0
CAJOBI                    0
CAMANDUCAIA               9
CAMPINAS                  0
CAMPOS DOS GOYTACAZES     0
CASIMIRO DE ABREU         0
CONFINS                   0
COROMANDEL                0
COSM?POLIS                0
DIAMANTINA                0
DIVIN?POLIS               0
GUARULHOS                 0
IPATINGA                  0
IPER?                     3
IT?POLIS                  0
ITANHA?M                  1
JUIZ DE FORA              0
JUNDIA?                   7
LINHARES                  0
MACA?                     0
MANGARATIBA               0
MAR?LIA                   0
MONTES CLAROS             0
NOVO HORIZONTE            3
OL?MPIA                   0
PAR? DE MINAS             0
PEN?POLIS                 0
PIACATU                   0
PIRACICABA                0
PIRASSUNUNGA              0
PO?OS DE CALDAS           0
POUSO ALEGRE              0
RESENDE                   8
RIBEIR?O PRETO            0
RIO DE JANEIRO           25
S?O BERNARDO DO CAMPO     2
S?O JOS? DO RIO PRETO     0
S?O JOS? DOS CAMPOS       0
S?O PAULO                41
SANTOS                    0
SERRA NEGRA               0
SOROCABA                  0
TIM?TEO                   3
UBERABA                   0
UBERL?NDIA                0
VIT?RIA                   0
Name: total_recomendacoes, dtype: int64

In [150]:
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
BOITUVA                   1
BOM JESUS DO GALHO        1
ITANHA?M                  1
BELO HORIZONTE            2
S?O BERNARDO DO CAMPO     2
IPER?                     3
NOVO HORIZONTE            3
TIM?TEO                   3
JUNDIA?                   7
RESENDE                   8
BRAGAN?A PAULISTA         9
CAMANDUCAIA               9
RIO DE JANEIRO           25
S?O PAULO                41
Name: total_recomendacoes, dtype: int64

In [154]:
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade',dfsudeste2010.ocorrencia_dia.dt.month]).total_recomendacoes.sum()

ocorrencia_cidade      ocorrencia_dia
BELO HORIZONTE         2                  1
                       3                  1
BOITUVA                7                  1
BOM JESUS DO GALHO     12                 1
BRAGAN?A PAULISTA      11                 9
CAMANDUCAIA            7                  9
IPER?                  1                  3
ITANHA?M               9                  1
JUNDIA?                5                  5
                       6                  2
NOVO HORIZONTE         7                  3
RESENDE                4                  8
RIO DE JANEIRO         4                  3
                       7                  3
                       8                 19
S?O BERNARDO DO CAMPO  1                  2
S?O PAULO              1                  8
                       2                 14
                       6                  2
                       11                 6
                       12                11
TIM?TEO                2                  3
Name: total_recomendacoes, dtype: int64

In [153]:
filtro1 = dfsudeste2010.total_recomendacoes > 0
filtro2 = dfsudeste2010.ocorrencia_cidade == 'S?O PAULO'
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
11,40069,40069,ACIDENTE,S?O PAULO,SP,SBMT,2010-01-10,14:50:00,8,2010-01-10 14:50:00
58,39275,39275,ACIDENTE,S?O PAULO,SP,NaN,2010-02-10,09:03:00,3,2010-02-10 09:03:00
63,39992,39992,ACIDENTE,S?O PAULO,SP,SBMT,2010-02-17,20:07:00,11,2010-02-17 20:07:00
219,41411,41411,INCIDENTE GRAVE,S?O PAULO,SP,SBMT,2010-06-08,19:30:00,2,2010-06-08 19:30:00
469,43450,43450,ACIDENTE,S?O PAULO,SP,SBMT,2010-11-04,10:55:00,6,2010-11-04 10:55:00
530,43471,43471,ACIDENTE,S?O PAULO,SP,NaN,2010-12-14,20:15:00,11,2010-12-14 20:15:00

In [156]:
filtro = df.ocorrencia_cidade.str[-1] == 'E'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2,2010-01-11 17:00:00
45,39316,39316,ACIDENTE,RIO DO OESTE,SC,NaN,2010-02-04,17:55:00,2,2010-02-04 17:55:00
46,39155,39155,INCIDENTE,BELO HORIZONTE,MG,NaN,2010-02-05,12:55:00,0,2010-02-05 12:55:00
69,39727,39727,INCIDENTE GRAVE,V?RZEA GRANDE,MT,SBCY,2010-02-23,19:42:00,0,2010-02-23 19:42:00
...,...,...,...,...,...,...,...,...,...,...
6073,80204,80204,INCIDENTE,RECIFE,PE,SBRF,2021-07-22,15:15:00,0,2021-07-22 15:15:00
6103,80242,80242,INCIDENTE,V?RZEA GRANDE,MT,SBCY,2021-08-10,13:50:00,0,2021-08-10 13:50:00
6105,80239,80239,INCIDENTE,BELO HORIZONTE,MG,SBBH,2021-08-11,19:58:00,0,2021-08-11 19:58:00
6107,80243,80243,INCIDENTE,BELO HORIZONTE,MG,SBBH,2021-08-15,17:14:00,0,2021-08-15 17:14:00
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0,2021-08-15 15:05:00